// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9EiWgy8ObKe5U0Gx0JTyYzBYAS7gQmI',
    appId: '1:789527738796:web:015eba294d7a4f519fa209',
    messagingSenderId: '789527738796',
    projectId: 'the-book-list-18073',
    authDomain: 'the-book-list-18073.firebaseapp.com',
    storageBucket: 'the-book-list-18073.appspot.com',
    measurementId: 'G-HTDK7M9275',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD355fXZTSyeWk-l7TdPrlbvwyY1sAG0cI',
    appId: '1:789527738796:android:0191e5d0c6e5a3389fa209',
    messagingSenderId: '789527738796',
    projectId: 'the-book-list-18073',
    storageBucket: 'the-book-list-18073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86DXCOZ2KcueSolcRFeZWCKbROLJc0pw',
    appId: '1:789527738796:ios:259678576811b9319fa209',
    messagingSenderId: '789527738796',
    projectId: 'the-book-list-18073',
    storageBucket: 'the-book-list-18073.appspot.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86DXCOZ2KcueSolcRFeZWCKbROLJc0pw',
    appId: '1:789527738796:ios:ed71ee1749bebad39fa209',
    messagingSenderId: '789527738796',
    projectId: 'the-book-list-18073',
    storageBucket: 'the-book-list-18073.appspot.com',
    iosBundleId: 'com.example.booksApp.RunnerTests',
  );
}
